const canvas=document.getElementById('scene');
const ctx=canvas.getContext('2d',{alpha:false});
const audio=document.getElementById('audio');
const playBtn=document.getElementById('playBtn');
const restartBtn=document.getElementById('restartBtn');
const recordBtn=document.getElementById('recordBtn');
const progressBar=document.getElementById('progressBar');
const timeNow=document.getElementById('timeNow');
const timeTotal=document.getElementById('timeTotal');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),particles=[],target=[],ambient=[],activeIndex=-1,lastT=0,transitioning=false,recording=false,recorder=null,chunks=[],audioCtx=null,sourceNode=null,recordDest=null;
const green={r:66,g:230,b:149};
const rand=(a,b)=>a+Math.random()*(b-a);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
const fmt=s=>{s=Math.max(0,Math.floor(s||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);buildAmbient();if(activeIndex>=0)setTarget(LYRICS[activeIndex].text,true)}
function buildAmbient(){ambient=[];const n=Math.floor(Math.min(900,Math.max(260,W*H/15000)));for(let i=0;i<n;i++)ambient.push({x:Math.random()*W,y:Math.random()*H,r:Math.random()<.9?rand(.3,1.15):rand(1.2,2.1),a:rand(.035,.18),p:Math.random()*Math.PI*2,s:rand(.2,1.2)});}
function sampleText(text){const off=document.createElement('canvas'),o=off.getContext('2d');const maxW=Math.min(W*.84,1100),fontSize=clamp(W/13,31,105);off.width=Math.ceil(maxW);off.height=Math.ceil(fontSize*1.55);o.clearRect(0,0,off.width,off.height);o.direction='rtl';o.textAlign='center';o.textBaseline='middle';o.font=`800 ${fontSize}px Tahoma, Arial, sans-serif`;o.fillStyle='#fff';o.fillText(text,off.width/2,off.height/2,maxW*.96);const data=o.getImageData(0,0,off.width,off.height).data;const step=Math.max(3,Math.round(fontSize/17));const pts=[];for(let y=0;y<off.height;y+=step){for(let x=0;x<off.width;x+=step){if(data[(y*off.width+x)*4+3]>110){pts.push({x:x-off.width/2,y:y-off.height/2})}}}return pts;}
function makeParticles(n){particles=[];for(let i=0;i<n;i++)particles.push({x:rand(0,W),y:rand(0,H),tx:W/2,ty:H/2,vx:0,vy:0,r:rand(.65,1.65),a:rand(.45,1),seed:Math.random()*10});}
function setTarget(text,instant=false){const pts=sampleText(text);if(!particles.length)makeParticles(Math.max(pts.length,1200));while(particles.length<pts.length)particles.push({x:rand(0,W),y:rand(0,H),tx:W/2,ty:H/2,vx:0,vy:0,r:rand(.65,1.65),a:rand(.45,1),seed:Math.random()*10});const baseY=H*.30;for(let i=0;i<particles.length;i++){const p=particles[i],q=pts[i%pts.length];p.tx=W/2+q.x;p.ty=baseY+q.y;p.homeX=p.tx;p.homeY=p.ty;if(instant){p.x=p.tx;p.y=p.ty}}target=pts;transitioning=!instant;}
function setMapTarget(){const points=[];const poly=[[-.55,-.35],[-.36,-.50],[-.08,-.43],[.18,-.55],[.45,-.35],[.56,-.08],[.48,.18],[.28,.34],[.08,.53],[-.18,.47],[-.34,.29],[-.53,.22],[-.48,.02],[-.63,-.10]];const cx=W/2,cy=H*.29,s=Math.min(W,H)*.43;for(let i=0;i<1600;i++){let u=Math.random(),v=Math.random();let inside=false;let px=0,py=0;while(!inside){px=rand(-.7,.7);py=rand(-.6,.65);inside=pointInPoly(px,py,poly)}points.push({x:px*s,y:py*s*.9})}for(let i=0;i<particles.length;i++){const q=points[i%points.length],p=particles[i];p.tx=cx+q.x;p.ty=cy+q.y;p.homeX=p.tx;p.homeY=p.ty}}
function pointInPoly(x,y,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i][0],yi=poly[i][1],xj=poly[j][0],yj=poly[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))c=!c}return c}
function drawCode(t){ctx.save();ctx.globalAlpha=.20;ctx.font=`${clamp(W/85,9,13)}px ui-monospace,SFMono-Regular,Menlo,monospace`;ctx.direction='ltr';const lines=["from dataclasses import dataclass","","PARTICLE_COLOR = '#42E695'","saudi_identity = {","  'generosity': 'مجدٌ وكرم',","  'authenticity': 'هويةٌ راسخة',","  'giving': 'عطاءٌ بلا حدود',","  'vision': 'طموحٌ إلى القمة',","  'courage': 'ثباتٌ وشجاعة',","  'ambition': 'نحو المستقبل',","}","","@dataclass","class Scene:","  shape: str","  start: float","  end: float","","def smooth_transition(t):"];for(let i=0;i<lines.length;i++){const y=H*.50+i*18;ctx.fillStyle=i===2?'rgba(66,230,149,.9)':i>3&&i<10?'rgba(115,242,171,.6)':'rgba(150,255,205,.38)';ctx.fillText(lines[i],W*.07,y)}ctx.restore()}
function drawOrb(t){const x=W/2,y=H*.63;ctx.save();for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(x,y,Math.min(W*.15,145)*(1+i*.34),7+i*2,0,0,Math.PI*2);ctx.fillStyle=`rgba(66,230,149,${.06-i*.012})`;ctx.shadowBlur=18;ctx.shadowColor='#42e695';ctx.fill()}ctx.restore()}
function drawParticles(t,dt){for(const p of particles){const dx=p.tx-p.x,dy=p.ty-p.y;const k=transitioning?.045:.075;p.vx=p.vx*.84+dx*k;p.vy=p.vy*.84+dy*k;p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;const wobble=Math.sin(t*1.8+p.seed)*.22;const near=Math.hypot(dx,dy);const alpha=clamp(p.a*(near<35?1:.78),.05,1);ctx.fillStyle=`rgba(${green.r},${green.g},${green.b},${alpha})`;ctx.shadowBlur=near<16?7:2;ctx.shadowColor='rgba(66,230,149,.55)';ctx.beginPath();ctx.arc(p.x+wobble,p.y+wobble,p.r,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0}
function scatter(){for(const p of particles){p.tx=rand(W*.15,W*.85);p.ty=rand(H*.16,H*.57);p.vx=rand(-1.8,1.8);p.vy=rand(-1.8,1.8)}transitioning=true}
function activeLyric(t){for(let i=0;i<LYRICS.length;i++)if(t>=LYRICS[i].start&&t<LYRICS[i].end)return i;return -1}
function render(ms){const t=ms/1000,dt=Math.min(.033,Math.max(.001,t-lastT));lastT=t;ctx.fillStyle='#010704';ctx.fillRect(0,0,W,H);const grad=ctx.createRadialGradient(W/2,H*.28,0,W/2,H*.28,Math.max(W,H)*.65);grad.addColorStop(0,'rgba(12,80,47,.11)');grad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);for(const a of ambient){const yy=a.y+Math.sin(t*a.s+a.p)*5;ctx.fillStyle=`rgba(66,230,149,${a.a})`;ctx.beginPath();ctx.arc(a.x,yy,a.r,0,Math.PI*2);ctx.fill()}drawCode(t);drawOrb(t);drawParticles(t,dt);if(audio.duration){progressBar.style.width=`${(audio.currentTime/audio.duration)*100}%`;timeNow.textContent=fmt(audio.currentTime);timeTotal.textContent=fmt(audio.duration)}requestAnimationFrame(render)}
function startPlayback(){audio.play().then(()=>{playBtn.textContent='إيقاف'}).catch(()=>{playBtn.textContent='تشغيل'})}
playBtn.onclick=()=>{if(audio.paused)startPlayback();else{audio.pause();playBtn.textContent='تشغيل'}};
restartBtn.onclick=()=>{audio.currentTime=0;activeIndex=-1;scatter();startPlayback()};
audio.addEventListener('loadedmetadata',()=>timeTotal.textContent=fmt(audio.duration));
audio.addEventListener('pause',()=>{if(!recording)playBtn.textContent='تشغيل'});
audio.addEventListener('ended',()=>{playBtn.textContent='تشغيل';scatter();setTimeout(()=>setTarget('مشروع الطالب راكان بن سعد القحطاني'),250)});
audio.addEventListener('timeupdate',()=>{const i=activeLyric(audio.currentTime);if(i!==activeIndex){activeIndex=i;if(i>=0)setTarget(LYRICS[i].text);else if(audio.currentTime>27.45)setTarget('مشروع الطالب راكان بن سعد القحطاني')}});
function initAudioGraph(){if(audioCtx)return;audioCtx=new AudioContext();sourceNode=audioCtx.createMediaElementSource(audio);recordDest=audioCtx.createMediaStreamDestination();sourceNode.connect(audioCtx.destination);sourceNode.connect(recordDest)}
recordBtn.onclick=async()=>{if(recording){recorder.stop();recording=false;recordBtn.textContent='تسجيل الفيديو';return}initAudioGraph();if(audioCtx.state==='suspended')await audioCtx.resume();const stream=canvas.captureStream(60);recordDest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const types=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];const mime=types.find(x=>MediaRecorder.isTypeSupported(x));if(!mime){alert('المتصفح لا يدعم تسجيل الفيديو من هذه الصفحة.');return}chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:mime});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='saudi-nasheed-particle.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)};recording=true;recordBtn.textContent='إيقاف التسجيل';audio.currentTime=0;startPlayback()};
canvas.addEventListener('click',()=>{if(audio.paused)startPlayback()});
addEventListener('resize',resize);resize();makeParticles(2600);setTarget(LYRICS[0].text,true);requestAnimationFrame(render);
